# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 604)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("border-radius: 10px")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: white;\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 3px solid black;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setFrame(True)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.PressButton_C = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_C.setGeometry(QtCore.QRect(20, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_C.setFont(font)
        self.PressButton_C.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_C.setObjectName("PressButton_C")
        self.PressButton_div = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_div.setGeometry(QtCore.QRect(100, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_div.setFont(font)
        self.PressButton_div.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_div.setObjectName("PressButton_div")
        self.PressButton_X = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_X.setGeometry(QtCore.QRect(180, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_X.setFont(font)
        self.PressButton_X.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_X.setObjectName("PressButton_X")
        self.PressButton_07 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_07.setGeometry(QtCore.QRect(20, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_07.setFont(font)
        self.PressButton_07.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_07.setObjectName("PressButton_07")
        self.PressButton_08 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_08.setGeometry(QtCore.QRect(100, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_08.setFont(font)
        self.PressButton_08.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}")
        self.PressButton_08.setObjectName("PressButton_08")
        self.PressButton_09 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_09.setGeometry(QtCore.QRect(180, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_09.setFont(font)
        self.PressButton_09.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}")
        self.PressButton_09.setObjectName("PressButton_09")
        self.PressButton_04 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_04.setGeometry(QtCore.QRect(20, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_04.setFont(font)
        self.PressButton_04.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_04.setObjectName("PressButton_04")
        self.PressButton_05 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_05.setGeometry(QtCore.QRect(100, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_05.setFont(font)
        self.PressButton_05.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_05.setObjectName("PressButton_05")
        self.PressButton_06 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_06.setGeometry(QtCore.QRect(180, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_06.setFont(font)
        self.PressButton_06.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_06.setObjectName("PressButton_06")
        self.PressButton_01 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_01.setGeometry(QtCore.QRect(20, 440, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_01.setFont(font)
        self.PressButton_01.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}")
        self.PressButton_01.setObjectName("PressButton_01")
        self.PressButton_02 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_02.setGeometry(QtCore.QRect(100, 440, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_02.setFont(font)
        self.PressButton_02.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_02.setObjectName("PressButton_02")
        self.PressButton_03 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_03.setGeometry(QtCore.QRect(180, 440, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_03.setFont(font)
        self.PressButton_03.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_03.setObjectName("PressButton_03")
        self.PressButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_0.setGeometry(QtCore.QRect(100, 510, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_0.setFont(font)
        self.PressButton_0.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_0.setObjectName("PressButton_0")
        self.PressButton_com = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_com.setGeometry(QtCore.QRect(180, 510, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_com.setFont(font)
        self.PressButton_com.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_com.setObjectName("PressButton_com")
        self.PressButton_sum = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_sum.setGeometry(QtCore.QRect(260, 370, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_sum.setFont(font)
        self.PressButton_sum.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_sum.setObjectName("PressButton_sum")
        self.PressButton_sub = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_sub.setGeometry(QtCore.QRect(260, 300, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_sub.setFont(font)
        self.PressButton_sub.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}")
        self.PressButton_sub.setObjectName("PressButton_sub")
        self.PressButton_CE = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_CE.setGeometry(QtCore.QRect(260, 230, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_CE.setFont(font)
        self.PressButton_CE.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_CE.setObjectName("PressButton_CE")
        self.PressButton_MC = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_MC.setGeometry(QtCore.QRect(20, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_MC.setFont(font)
        self.PressButton_MC.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_MC.setObjectName("PressButton_MC")
        self.PressButton_Msum = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_Msum.setGeometry(QtCore.QRect(100, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_Msum.setFont(font)
        self.PressButton_Msum.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_Msum.setObjectName("PressButton_Msum")
        self.PressButton_Msub = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_Msub.setGeometry(QtCore.QRect(180, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_Msub.setFont(font)
        self.PressButton_Msub.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_Msub.setObjectName("PressButton_Msub")
        self.PressButton_MR = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_MR.setGeometry(QtCore.QRect(260, 160, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_MR.setFont(font)
        self.PressButton_MR.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_MR.setObjectName("PressButton_MR")
        self.PressButton_perc = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_perc.setGeometry(QtCore.QRect(20, 510, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_perc.setFont(font)
        self.PressButton_perc.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}\n"
"")
        self.PressButton_perc.setObjectName("PressButton_perc")
        self.PressButton_Eq = QtWidgets.QPushButton(self.centralwidget)
        self.PressButton_Eq.setGeometry(QtCore.QRect(260, 440, 71, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PressButton_Eq.setFont(font)
        self.PressButton_Eq.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border: 3px solid #55aaff;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #61e2ff;\n"
"}")
        self.PressButton_Eq.setObjectName("PressButton_Eq")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 311, 51))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PressButton_C.setText(_translate("MainWindow", "C"))
        self.PressButton_div.setText(_translate("MainWindow", "/"))
        self.PressButton_X.setText(_translate("MainWindow", "x"))
        self.PressButton_07.setText(_translate("MainWindow", "7"))
        self.PressButton_08.setText(_translate("MainWindow", "8"))
        self.PressButton_09.setText(_translate("MainWindow", "9"))
        self.PressButton_04.setText(_translate("MainWindow", "4"))
        self.PressButton_05.setText(_translate("MainWindow", "5"))
        self.PressButton_06.setText(_translate("MainWindow", "6"))
        self.PressButton_01.setText(_translate("MainWindow", "1"))
        self.PressButton_02.setText(_translate("MainWindow", "2"))
        self.PressButton_03.setText(_translate("MainWindow", "3"))
        self.PressButton_0.setText(_translate("MainWindow", "0"))
        self.PressButton_com.setText(_translate("MainWindow", "."))
        self.PressButton_sum.setText(_translate("MainWindow", "+"))
        self.PressButton_sub.setText(_translate("MainWindow", "-"))
        self.PressButton_CE.setText(_translate("MainWindow", "CE"))
        self.PressButton_MC.setText(_translate("MainWindow", "MC"))
        self.PressButton_Msum.setText(_translate("MainWindow", "M+"))
        self.PressButton_Msub.setText(_translate("MainWindow", "M-"))
        self.PressButton_MR.setText(_translate("MainWindow", "MR"))
        self.PressButton_perc.setText(_translate("MainWindow", "%"))
        self.PressButton_Eq.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
